theme: jekyll-theme-minimal
logo: ./image/ProfilePicture.jpg
title: Giannos Louloudis
description: Bioinformatics, Software Development, Data Science
email: giannos.louloudis@gmail.com
permalink: Giannos Louloudis

class:
  - bg-light-gray

footer_navigation:
  -title: Hello world!
  -url: giannos.louloudis@gmail.com